# Generated by Django 3.0 on 2020-06-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING')], default='PENDING', max_length=10),
        ),
    ]
